# Uses https://github.com/dorny/paths-filter to determine what files were changed in a commit and then creates a GitHub Check
# for the commit that corresponds to the type of files that were changed: "only frontend", "only backend", "fullstack"
#
# This is used in sentry + getsentry, and requires a `.github/file-filters.yml` configuration with a `frontend` and `backend` collection.
#
name: "Check What Changed"
description: 'Adds a GitHub Check to a commit that corresponds to the types of files that were changed ("only frontend", "only backend", "fullstack")'
runs:
  using: composite

  steps:
  - name: Check for file changes
    uses: getsentry/paths-filter@master
    id: changes
    with:
      list-files: shell
      token: ${{ github.token }}
      filters: .github/file-filters.yml

  - name: Create GitHub job
    uses: actions/github-script@v5
    with:
      script: |
        require('${{ github.action_path }}/deploy.js').updateChangeType({
          github,
          context,
          fileChanges: ${{ toJson(steps.changes.outputs) }}
        });
